export const PRODUCT_LIST = [
  "Vehicle Gateway",
  "Road-Facing AI Dashcam Plus – Safety",
  "Road-Facing AI Dashcam Plus – Fleet Management",
  "Dual-Facing AI Dashcam Plus – Safety",
  "Dual-Facing AI Dashcam Plus – Fleet Management",
  "Non SA VG + AI RFDC Bundle",
  "Non SA VG + AI DFDC Bundle",
  "Asset Gateway Mini (Un-Cabled)",
  "Asset Gateway Mini Cable",
  "Asset Gateway Mini (Cabled Bundle)",
  "Smart Road-facing Dashcam",
  "Smart Dual-facing Dashcam",
  "Smart SA Road-facing Dashcam",
  "Smart SA Dual-facing Dashcam",
  "AI Road-facing Dashcam",
  "AI Dual-facing Dashcam",
  "AI SA Road-facing Dashcam",
  "AI SA Dual-facing Dashcam",
  "Omnicam",
  "Wifi",
  "ES2 Sensor",
  "Engine Immobilizer",
  "Workforce Management",
  "Thermoking API License",
  "Carrier Transicold License",
  "Ford Pro",
  "AEMP 2.0",
  "Motive Beacon",
  "RFID Reader",
  "Door & Environmental Sensor"
];

export const MOCK_IMAGE = "https://picsum.photos/400/300";